aliases:
  - &system-deps
      name: System dependencies
      command: |
        sudo apt-get update
        sudo apt -y install build-essential libldap2-dev
  - &install
      name: Install
      command: |
        ls ~/.pyenv || curl https://pyenv.run | bash
        export PATH="~/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        scripts/install.sh
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.3
    working_directory: ~/project
    steps:
      - checkout
      - run: *system-deps
      - restore_cache:
          keys:
            - dep-{{ .Environment.CACHE_VERSION }}-{{ checksum "requirements.txt" }}-{{ checksum ".python-version"}}
      - run: *install
      - save_cache:
          key: dep-{{ .Environment.CACHE_VERSION }}-{{ checksum "requirements.txt" }}-{{ checksum ".python-version"}}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv
      - run:
          name: CI tasks
          command: |
            export PATH="~/.pyenv/bin:$PATH"
            eval "$(pyenv init --path)"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            scripts/setup_python.sh
            invoke ci
workflows:
  build-workflow:
    jobs:
      - build:
          context:
            - SalaryScrapy
          filters:
            tags:
              only: /.*/
